language: csharp
solution: Digitaler Einsatzbericht.sln
dist: bionic
mono: none
dotnet: 2.2.105
stages:
  - build
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
after_success:
- curl --ftp-create-dirs -T filename ftp://${SFTP_USER}:${SFTP_PASSWORD}@137.117.160.145/var/www/filename
