language: csharp
solution: Digitaler Einsatzbericht.sln
dist: bionic
mono: none
dotnet: 2.2.105
stages:
  - build
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
