os:
  - linux
  - windows
  - osx
language: csharp
solution: Digitaler Einsatzbericht.sln
dotnet: 2.2.105


matrix:
    include:
        - os: linux
          dist: bionic
          mono: none
    allow_failures:
        - os: osx
          linux: linux
          windows: windows
stages:
  - build
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
